<?php
// Code for carousel module
function myplugin_theme($existing, $type, $theme, $path){
    return [
        'myplugin' => [
            'variables' => [
                'photo_1' => null,
                'quote_1' => null,
                'citation_1' => null,
                'test_string' => 'init test string state'
            ],
                'template' => 'block--hero-carousel'
        ]
    ];
}