<?php
/**
 * @file
 * Contains thm_related_makers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\search_api\Entity\Index;
use Drupal\node\NodeInterface;
use Drupal\file\Entity\File;
use Drupal\taxonomy\Entity\Term;

function mypluginBanner_theme($existing, $type, $theme, $path){
  return [
    'mypluginBanner' => [
      'variables' => [
        'background_color' => $background_color, 
        'feature_name' => $feature_name,       
        'feature_occupation' => $feature_occupation, 
        'feature_image' => $feature_image, 
        'sponsor_name' => $sponsor_name, 
        'sponsor_image' => $sponsor_image, 
      ],
        'template' => 'block--page-banner'
    ]
  ];

} //The End
