<?php

/**
 * @file
 * Contains thm_user_maker_matcher.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function thm_user_maker_matcher_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the thm_user_maker_matcher module.
    case 'help.page.thm_user_maker_matcher':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Maps common experiences and attributes between users and makers.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function thm_user_maker_matcher_theme() {
  return [
    'thm_user_maker_matcher' => [
      'render element' => 'children',
    ],
  ];
}
