<?php

/**
 * @file
 * Contains thm_user_maker_matcher.module.
 */

use Drupal\views\ViewExecutable;
use Drupal\Core\Routing\RouteMatchInterface as RMI;

/**
 * Implements hook_help().
 */
function thm_user_maker_matcher_help($route_name, RMI $route_match) {
  switch ($route_name) {
    // Main module help for the thm_user_maker_matcher module.
    case 'help.page.thm_user_maker_matcher':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Maps common experiences and attributes between users and makers.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function thm_user_maker_matcher_theme() {
  return [
    'thm_user_maker_matcher' => [
      'variables' => [
        'data' => null,
        'result_count' => null,
        'search_field' => null,
        'search_entry' => null,
        'base_url' => \Drupal::request()->getHost()
      ]
    ],
  ];
}

function _getExposedFilters() {
  return [
    'field_favorite_season',
    'field_favorite_color',
    'field_favorite_food',
    'field_favorite_vacation'
  ];
}

/**
 * Implements hook_views_pre_render().
 *
 * This particular implementation hides a view's exposed filters.
 *
 * @param ViewExecutable $view
 */
function thm_user_maker_matcher_views_pre_render(ViewExecutable $view) {
  if ($view->id() === 'matching_favorites' && $view->current_display === 'page_1') {

    $view->exposed_widgets['actions']['submit']['#access'] = false;

    foreach(_getExposedFilters() as $filter) {
      $view->exposed_widgets[$filter]['#access'] = false;
    }
  }
}

