<?php
// Code for Angular Module
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\file\Entity\File;

function thm_hero_video_player_theme($existing, $type, $theme, $path){
    return [
        'angular' => [
            'variables' => [
                'video' => null
            ],
            'template' => 'block--hero-video-player-block'
        ]
    ];
}

function thm_hero_video_player_get_current_node() {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof NodeInterface) {
      return $node;
    } else {
      return false;
    }
  }

function thm_hero_video_player_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] =
        'thm_hero_video_player/thm_hero_video_player';
}
