<?php
/**
 * Created by PhpStorm.
 * User: t2
 * Date: 9/27/18
 * Time: 1:41 PM
 */

use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Form\FormStateInterface as FSI;


/**
 * Implements hook_entity_update().
 *
 * @param $entity EntityInterface
 * @return bool|\Symfony\Component\HttpFoundation\RedirectResponse
 */
function thm_user_actions_entity_update(EntityInterface $entity) {
  $entityType = $entity->getEntityTypeId();
  $uid = $entity->id();

  if ($entityType === 'user') {
    $response = new RedirectResponse("/user/$uid");
    $response->send();
  } else {
    return false;
  }
}


/**
 * Implements hook_form_alter().
 *
 * This particular hook is used to inject a JS file that will unbind the user
 * account form ajax functionality.
 *
 * @param array $form
 * @param FSI $form_state
 * @param string $form_id
 */
function thm_user_actions_form_user_form_alter(&$form, FSI $form_state, $form_id) {
  $form['#attached']['library'] = 'thm_user_actions/ajax_form_disabler';
}
