<?php
/**
 * Created by PhpStorm.
 * User: t2
 * Date: 9/27/18
 * Time: 1:41 PM
 */

use Drupal\Core\Entity\EntityInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;


/**
 * Implements hook_entity_update().
 *
 * @param $entity EntityInterface
 * @return bool|\Symfony\Component\HttpFoundation\RedirectResponse
 */
function thm_user_actions_entity_update(EntityInterface $entity) {
  $entityType = $entity->getEntityTypeId();
  $uid = $entity->id();

  if ($entityType === 'user') {
    $response = new RedirectResponse("/user/$uid");
    $response->send();
  } else {
    return false;
  }
}

/**
 * Implements hook_entity_create().
 */
function thm_user_actions_entity_create(EntityInterface $entity) {
  $entityType = $entity->getEntityTypeId();
  $uid = $entity->id();
  $entity->label();

  if ($entityType === 'user') {
    drupal_set_message('created ' . $entity->label());
  }
}