<?php
/**
 * Created by PhpStorm.
 * User: t2
 * Date: 3/28/18
 * Time: 3:39 PM
 */

namespace Drupal\thm_user_maker_matcher\Plugin\WebformHandler;

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Plugin\WebformHandlerBase;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Form submission handler.
 *
 * Takes submission values and performs a search, potentially matching against
 * Biography data.  Any hits are stored in a computed field.
 *
 * @WebformHandler(
 *   id = "thm_user_maker_matcher_handler",
 *   label = @Translation("MakerMatcher Handler"),
 *   category = @Translation("Submission Redirector"),
 *   description = @Translation("Routes submission data to another submission"),
 *   cardinality = \Drupal\webform\Plugin\WebformHandlerInterface::CARDINALITY_SINGLE,
 *   results = \Drupal\webform\Plugin\WebformHandlerInterface::RESULTS_PROCESSED,
 *   submission = \Drupal\webform\Plugin\WebformHandlerInterface::SUBMISSION_REQUIRED,
 * )
 */
class MakerMatcherWebformHandler extends WebformHandlerBase {
  public function submitForm(array &$form, FormStateInterface $form_state, WebformSubmissionInterface $webform_submission) {
    parent::submitForm($form, $form_state, $webform_submission); // TODO: Change the autogenerated stub
  }
}