<?php
/**
 * Created by PhpStorm.
 * User: t2
 * Date: 5/15/18
 * Time: 4:22 PM
 */

namespace Drupal\thm_adv_search\Plugin\facets\widget;

use Drupal\Core\Form\FormStateInterface;
use Drupal\facets\FacetInterface;
use Drupal\facets\Widget\WidgetPluginBase;


/**
 * Class AutoComplete
 *
 * @package Drupal\thm_adv_search\Plugin\facets\widget
 *
 * @FacetsWidget(
 *   id = "autocomplete_widget",
 *   label = @Translation("AutoCompleteWidget"),
 *   description = @Translation("An autocomplete widget.")
 * )
 */
class AutoCompleteWidget extends WidgetPluginBase {
  public function defaultConfiguration() {
    return parent::defaultConfiguration(); // TODO: Change the autogenerated stub
  }

  public function build(FacetInterface $facet) {
    return parent::build($facet); // TODO: Change the autogenerated stub
  }

  public function buildConfigurationForm(array $form, FormStateInterface $form_state, FacetInterface $facet) {
    return parent::buildConfigurationForm($form, $form_state, $facet); // TODO: Change the autogenerated stub
  }

  public function getQueryType() {
    return parent::getQueryType(); // TODO: Change the autogenerated stub
  }

  public function isPropertyRequired($name, $type) {
    return parent::isPropertyRequired($name, $type); // TODO: Change the autogenerated stub
  }
}