<?php
// Code for Angular Module
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\NodeInterface;
use Drupal\file\Entity\File;

function thm_angular_theme($existing, $type, $theme, $path){
    return [
        'angular' => [
            'variables' => [
                'video' => null
            ]
        ]
    ];
}

function thm_angular_get_current_node() {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof NodeInterface) {
      return $node;
    } else {
      return false;
    }
  }

function thm_angular_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] =
        'thm_angular/thm_angular';
}
