<?php
// Code for Angular Module
function thm_angular_theme($existing, $type, $theme, $path){
    return [
        'angular' => [
            'variables' => [
                'node' => thm_related_makers_get_current_node()
            ],
            'template' => 'block--angular-block'
        ]
    ];
}

function thm_angular_page_attachments(array &$attachments) {
    $attachments['#attached']['library'][] =
        'thm_angular/thm_angular';
}
