<?php

/**
 * @file
 * Contains thm_adv_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface as RMI;

/**
 * Implements hook_help().
 */
function thm_adv_search_help($route_name, RMI $route_match) {
  switch ($route_name) {
    // Main module help for the thm_adv_search module.
    case 'help.page.thm_adv_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('custom modifications supporting search functionality') . '</p>';
      return $output;

    default:
  }
}
